plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.20'
    id 'maven-publish'
    id 'idea'
}

version = "${mod_version}"
group = mod_group

base {
    archivesName = "${mod_id}-fabric"
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
    maven {
        name = 'BlameJared'
        url = 'https://maven.blamejared.com'
    }
    maven {
        name = 'Aether Cumulus'
        url = 'https://packages.aether-mod.net/Cumulus'
    }
    maven {
        name = 'Fuzs Maven'
        url = 'https://raw.githubusercontent.com/Fuzss/modresources/main/maven/'
    }
    maven {
        name = 'Shedaniel'
        url = 'https://maven.shedaniel.me/'
    }
    maven {
        name = 'CurseMaven'
        url = 'https://www.cursemaven.com'
    }
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}


dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation "com.aetherteam.nitrogen:nitrogen_internals-fabric:${nitrogen_version}"
    implementation "com.aetherteam.cumulus:cumulus_menus:${cumulus_version}"
    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forge_config_api_port_version}"

    compileOnly "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"
    compileOnly "maven.modrinth:sodium:mc26.2-0.9.2-fabric"
    compileOnly "com.google.code.findbugs:jsr305:3.0.2"
}

fabricApi {
    configureDataGeneration {
        client = true
        outputDirectory = file("src/generated/resources")
    }
}

loom {
    accessWidenerPath = file("src/main/resources/aether_ii.accesswidener")
}

processResources {
    exclude '.cache/'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << "-Xmaxerrs" << "9000"
}

tasks.register('sourceJar', Jar) {
    dependsOn 'classes'
    from sourceSets.main.allSource
    archiveClassifier = 'sources'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId project.base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = "https://maven.pkg.github.com/The-Aether-Team/The-Aether-II"
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}