package com.aetherteam.aetherii.data.providers;

import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.HolderOwner;
import net.minecraft.resources.ResourceKey;

/**
 * References to elements of reloadable registries (loot tables, recipes) that are generated by other providers and
 * therefore are not present in the datagen registry lookup.
 */
public final class DatagenReferences {
    private DatagenReferences() {
    }

    /**
     * A stand-alone reference that serializes as the key. The datagen lookups are {@code EmptyTagLookupWrapper}
     * delegates whose {@code canSerialize} check is forwarded to the wrapped registry, so the reference has to be
     * owned by the innermost lookup or the registry ops rejects it as "not valid in current registry set".
     */
    public static <T> Holder<T> reference(HolderLookup.RegistryLookup<T> lookup, ResourceKey<T> key) {
        HolderOwner<T> owner = lookup;
        while (owner instanceof HolderLookup.RegistryLookup.Delegate<T> delegate) {
            owner = delegate.parent();
        }
        return Holder.Reference.createStandAlone(owner, key);
    }
}
